/** Neighbourhoods, roads, and landmarks the Photon index often misses in Kano. */
export const KANO_PLACES: {
  name: string;
  aliases: string[];
  area: string;
  lat: number;
  lng: number;
}[] = [
  { name: "Sabon Gari", aliases: ["sabon gari", "sabongari"], area: "Fagge", lat: 12.0185, lng: 8.5382 },
  { name: "France Road, Sabon Gari", aliases: ["france road"], area: "Sabon Gari", lat: 12.0145, lng: 8.5436 },
  { name: "Sabon Gari Market", aliases: ["sabon gari market", "abubakar rimi market"], area: "Fagge", lat: 12.0168, lng: 8.5364 },
  { name: "Kantin Kwari", aliases: ["kwari", "kantin kwari", "kwari market", "textile market"], area: "Fagge", lat: 12.0018, lng: 8.5312 },
  { name: "Kurmi Market", aliases: ["kurmi", "kurmi market"], area: "Kano Municipal", lat: 11.9954, lng: 8.5168 },
  { name: "Bompai", aliases: ["bompai"], area: "Nassarawa", lat: 12.008, lng: 8.547 },
  { name: "Club Road, Bompai", aliases: ["club road"], area: "Bompai", lat: 12.017, lng: 8.548 },
  { name: "Nassarawa GRA", aliases: ["gra", "nassarawa gra", "nassarawa"], area: "Nassarawa", lat: 11.996, lng: 8.556 },
  { name: "Farm Centre", aliases: ["farm center", "farm centre"], area: "Tarauni", lat: 11.985, lng: 8.548 },
  { name: "Tarauni", aliases: ["tarauni"], area: "Tarauni", lat: 11.978, lng: 8.545 },
  { name: "Zoo Road", aliases: ["zoo road"], area: "Tarauni", lat: 11.9707, lng: 8.5324 },
  { name: "Kano Zoological Garden", aliases: ["kano zoo", "zoo"], area: "Tarauni", lat: 11.9674, lng: 8.5261 },
  { name: "Ado Bayero Mall", aliases: ["ado bayero", "shoprite", "shoprite kano"], area: "Gandu", lat: 11.9773, lng: 8.5345 },
  { name: "Gandu", aliases: ["gandu", "gandu albasa"], area: "Kano Municipal", lat: 11.972, lng: 8.53 },
  { name: "Hotoro", aliases: ["hotoro"], area: "Nassarawa", lat: 11.989, lng: 8.568 },
  { name: "Naibawa", aliases: ["naibawa"], area: "Kumbotso", lat: 11.963, lng: 8.555 },
  { name: "Gyadi-Gyadi", aliases: ["gyadi", "gyadi gyadi"], area: "Tarauni", lat: 11.978, lng: 8.535 },
  { name: "Sharada Industrial Estate", aliases: ["sharada"], area: "Gwale", lat: 11.978, lng: 8.5 },
  { name: "Gwale", aliases: ["gwale"], area: "Gwale", lat: 11.991, lng: 8.505 },
  { name: "Dala", aliases: ["dala"], area: "Dala", lat: 12.01, lng: 8.51 },
  { name: "Fagge", aliases: ["fagge"], area: "Fagge", lat: 12.008, lng: 8.535 },
  { name: "Kano Municipal", aliases: ["kano municipal", "municipal", "kmc"], area: "Kano", lat: 11.996, lng: 8.522 },
  { name: "Kumbotso", aliases: ["kumbotso"], area: "Kumbotso", lat: 11.89, lng: 8.503 },
  { name: "Ungogo", aliases: ["ungogo"], area: "Ungogo", lat: 12.092, lng: 8.496 },
  { name: "Kofar Ruwa", aliases: ["kofar ruwa"], area: "Dala", lat: 12.015, lng: 8.508 },
  { name: "Kofar Wambai", aliases: ["kofar wambai"], area: "Municipal", lat: 12.002, lng: 8.52 },
  { name: "Kofar Mata", aliases: ["kofar mata"], area: "Municipal", lat: 11.999, lng: 8.519 },
  { name: "Kofar Nassarawa", aliases: ["kofar nassarawa"], area: "Municipal", lat: 11.993, lng: 8.53 },
  { name: "Gwagwarwa", aliases: ["gwagwarwa"], area: "Nassarawa", lat: 12.022, lng: 8.56 },
  { name: "Dakata", aliases: ["dakata"], area: "Nassarawa", lat: 12.02, lng: 8.57 },
  { name: "Kawaji", aliases: ["kawaji"], area: "Nassarawa", lat: 12.005, lng: 8.562 },
  { name: "Dorayi", aliases: ["dorayi"], area: "Gwale", lat: 11.985, lng: 8.48 },
  { name: "Rijiyar Zaki", aliases: ["rijiyar zaki"], area: "Ungogo", lat: 12.04, lng: 8.47 },
  { name: "Panshekara", aliases: ["panshekara"], area: "Kumbotso", lat: 11.91, lng: 8.47 },
  { name: "Murtala Mohammed Way", aliases: ["murtala mohammed way", "murtala way"], area: "Fagge", lat: 12.008, lng: 8.533 },
  { name: "Zaria Road", aliases: ["zaria road"], area: "Tarauni", lat: 11.97, lng: 8.54 },
  { name: "Katsina Road", aliases: ["katsina road"], area: "Dala", lat: 12.03, lng: 8.515 },
  { name: "Hadejia Road", aliases: ["hadejia road"], area: "Nassarawa", lat: 12.01, lng: 8.56 },
  { name: "Ibrahim Taiwo Road", aliases: ["ibrahim taiwo", "taiwo road"], area: "Municipal", lat: 11.998, lng: 8.528 },
  { name: "Ahmadu Bello Way", aliases: ["ahmadu bello way"], area: "Nassarawa", lat: 12.0, lng: 8.55 },
  { name: "Mallam Aminu Kano International Airport", aliases: ["airport", "aminu kano airport", "makia"], area: "Ungogo", lat: 12.0469, lng: 8.5213 },
  { name: "Bayero University Kano", aliases: ["buk", "bayero", "bayero university"], area: "Gwale", lat: 11.973, lng: 8.427 },
  { name: "Aminu Kano Teaching Hospital", aliases: ["akth", "teaching hospital"], area: "Tarauni", lat: 11.979, lng: 8.54 },
  { name: "Emir's Palace", aliases: ["emir palace", "gidan rumfa", "emir's palace"], area: "Municipal", lat: 11.9958, lng: 8.5164 },
  { name: "Kano State Government House", aliases: ["government house", "govt house"], area: "Municipal", lat: 11.992, lng: 8.53 },
  { name: "Sani Abacha Stadium", aliases: ["sani abacha stadium", "stadium"], area: "Municipal", lat: 12.002, lng: 8.53 },
  { name: "Gidan Murtala", aliases: ["gidan murtala"], area: "Municipal", lat: 11.994, lng: 8.525 },
  { name: "Wudil", aliases: ["wudil"], area: "Wudil", lat: 11.809, lng: 8.844 },
  { name: "Gwarzo", aliases: ["gwarzo"], area: "Gwarzo", lat: 11.916, lng: 7.934 },
  { name: "Rano", aliases: ["rano"], area: "Rano", lat: 11.557, lng: 8.745 },
  { name: "Bichi", aliases: ["bichi"], area: "Bichi", lat: 12.234, lng: 8.241 },
  { name: "Dawakin Tofa", aliases: ["dawakin tofa"], area: "Dawakin Tofa", lat: 12.105, lng: 8.33 },
  { name: "Gezawa", aliases: ["gezawa"], area: "Gezawa", lat: 12.077, lng: 8.749 },
  { name: "Minjibir", aliases: ["minjibir"], area: "Minjibir", lat: 12.178, lng: 8.655 },
  { name: "Kura", aliases: ["kura"], area: "Kura", lat: 11.772, lng: 8.43 },
];
