/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PayRouteImport } from './routes/pay'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SendRouteImport } from './routes/send'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminFleetsRouteImport } from './routes/admin/fleets'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminRecordsRouteImport } from './routes/admin/records'
import { Route as AdminSendersRouteImport } from './routes/admin/senders'
import { Route as ApiTilesRouteImport } from './routes/api/tiles'
import { Route as JobJobIdRouteImport } from './routes/job.$jobId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFleetsRoute = AdminFleetsRouteImport.update({
  id: '/fleets',
  path: '/fleets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSendersRoute = AdminSendersRouteImport.update({
  id: '/senders',
  path: '/senders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiTilesRoute = ApiTilesRouteImport.update({
  id: '/api/tiles',
  path: '/api/tiles',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdRoute = JobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/pay': typeof PayRoute
  '/request': typeof RequestRoute
  '/send': typeof SendRoute
  '/track': typeof TrackRoute
  '/admin/fleets': typeof AdminFleetsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/senders': typeof AdminSendersRoute
  '/api/tiles': typeof ApiTilesRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/pay': typeof PayRoute
  '/request': typeof RequestRoute
  '/send': typeof SendRoute
  '/track': typeof TrackRoute
  '/admin/fleets': typeof AdminFleetsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/senders': typeof AdminSendersRoute
  '/api/tiles': typeof ApiTilesRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/pay': typeof PayRoute
  '/request': typeof RequestRoute
  '/send': typeof SendRoute
  '/track': typeof TrackRoute
  '/admin/fleets': typeof AdminFleetsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/senders': typeof AdminSendersRoute
  '/api/tiles': typeof ApiTilesRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/contact'
    | '/jobs'
    | '/login'
    | '/ops'
    | '/pay'
    | '/request'
    | '/send'
    | '/track'
    | '/admin/fleets'
    | '/admin/jobs'
    | '/admin/map'
    | '/admin/payments'
    | '/admin/records'
    | '/admin/senders'
    | '/api/tiles'
    | '/job/$jobId'
    | '/admin/'
    | '/api/auth/$'
    | '/api/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/contact'
    | '/jobs'
    | '/login'
    | '/ops'
    | '/pay'
    | '/request'
    | '/send'
    | '/track'
    | '/admin/fleets'
    | '/admin/jobs'
    | '/admin/map'
    | '/admin/payments'
    | '/admin/records'
    | '/admin/senders'
    | '/api/tiles'
    | '/job/$jobId'
    | '/admin'
    | '/api/auth/$'
    | '/api/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account'
    | '/contact'
    | '/jobs'
    | '/login'
    | '/ops'
    | '/pay'
    | '/request'
    | '/send'
    | '/track'
    | '/admin/fleets'
    | '/admin/jobs'
    | '/admin/map'
    | '/admin/payments'
    | '/admin/records'
    | '/admin/senders'
    | '/api/tiles'
    | '/job/$jobId'
    | '/admin/'
    | '/api/auth/$'
    | '/api/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  PayRoute: typeof PayRoute
  RequestRoute: typeof RequestRoute
  SendRoute: typeof SendRoute
  TrackRoute: typeof TrackRoute
  ApiTilesRoute: typeof ApiTilesRoute
  JobJobIdRoute: typeof JobJobIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fleets': {
      id: '/admin/fleets'
      path: '/fleets'
      fullPath: '/admin/fleets'
      preLoaderRoute: typeof AdminFleetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/senders': {
      id: '/admin/senders'
      path: '/senders'
      fullPath: '/admin/senders'
      preLoaderRoute: typeof AdminSendersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/tiles': {
      id: '/api/tiles'
      path: '/api/tiles'
      fullPath: '/api/tiles'
      preLoaderRoute: typeof ApiTilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId': {
      id: '/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/job/$jobId'
      preLoaderRoute: typeof JobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminFleetsRoute: typeof AdminFleetsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminSendersRoute: typeof AdminSendersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFleetsRoute: AdminFleetsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMapRoute: AdminMapRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminSendersRoute: AdminSendersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  PayRoute: PayRoute,
  RequestRoute: RequestRoute,
  SendRoute: SendRoute,
  TrackRoute: TrackRoute,
  ApiTilesRoute: ApiTilesRoute,
  JobJobIdRoute: JobJobIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
